version: '3'

services:
  db-test:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  cred-schema-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db-test
    environment:
      DATABASE_URL: postgres://postgres:postgres@db-test:5432/postgres