apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak-service
  name: keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-service
  strategy: {}
  template:
    metadata:
      labels:
        app: keycloak-service
    spec:
      containers:
        - image: dockerhub/sunbird-rc-keycloak:latest
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - curl -f http://localhost:8080/ || exit 1
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "2G"
          name: keycloak-service
          envFrom:
            - configMapRef:
                name: rc-config
          env:
            - name: JAVA_OPTS
              value: "-server -Xms64m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED"
      restartPolicy: Always

