swagger: '2.0'
info:
  version: 1.0.0
  title: Digilocker Certificate API
  description: Pull Credentials to Digilocker
security: []
consumes:
  - application/xml
paths:
  /heath:
    get:
      tags: ["health"]
      summary: Get the health status
      description: API to get the notification health status
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/HealthOKResponse"
  /v1/digilocker/pullUriRequest:
    post:
      tags: ["pull certificates"]
      summary: Pull certificates in digilocker
      description: API to pull the credentials in digilocker
      consumes:
        - application/xml
      produces:
        - application/xml
      parameters:
        - in: body
          name: body
          description: PullUriRequest
          schema:
            $ref: "#/definitions/PullURIRequest"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/PullURIRequestOKResponse"

definitions:
  HealthOKResponse:
    type: object
    properties:
      status: 
        type: string
  PullURIRequestOKResponse:
    type: object
    properties:
      XMLName:
        type: string
      Text:
        type: string
      Ns2:
        type: string
      ResponseStatus:
        type: object
        properties:
          Text:
            type: string
          Status:
            type: string
          Ts:
            type: string
          Txn:
            type: string
      DocDetails:
        type: object
        properties:
          Text:
            type: string
          DocType:
            type: string
          DigiLockerId:
            type: string
          UID:
            type: string
          FullName:
            type: string
          DOB:
            type: string
          Mobile:
            type: string
          CertificateId:
            type: string
          UDF1:
            type: string
          URI:
            type: string
          DocContent:
            type: string
          DataContent:
            type: string
  PullURIRequest:
    type: object
    properties:
      XMLName:
        type: string
      Text:
        type: string
      Ns2:
        type: string
      Ver:
        type: string
      Ts:
        type: string
      Txn:
        type: string
      OrgId:
        type: string
      Format:
        type: string
      DocDetails:
        type: object
        properties:
          Text:
            type: string
          DocType:
            type: string
          DigiLockerId:
            type: string
          UID:
            type: string
          FullName:
            type: string
          DOB:
            type: string
          Photo:
            type: string
          TrackingId:
            type: string
          Mobile:
            type: string
          CertificateId:
            type: string
          UDF1:
            type: string
          UDF2:
            type: string
          UDF3:
            type: string
          UDFn:
            type: string              
      