swagger: '2.0'
info:
  version: 1.0.0
  title: Open Saber RC API
  description: Electronic Registries and Verifiable Credentials
securityDefinitions:
  hasRole:
    # This scheme uses the header: "Authorization: Bearer {base64 encoded string representing a JWT}"
    # Alternatively, the query param: "access_token" may be used.
    #
    # In our scenario, we must use the query param version in order to avoid
    # passing several headers with key 'Authorization'
    type: oauth2
    # The flow and URLs in spec are for documentary purpose: go-swagger does not implement OAuth workflows
    flow: accessCode
    authorizationUrl: 'https://dummy.oauth.net/auth'
    tokenUrl: 'https://dumy.oauth.net/token'
    # Required scopes are passed by the runtime to the authorizer
    scopes:
      admin: scope of super admin
      facility-admin: scope of facility admin

security:
  - hasRole: ['admin']
consumes:
  - application/json
produces:
  - application/json
paths:
  /register:
    post:
      summary: Register new entry
      operationId: register
      parameters:
        - in: body
          name: body
          type: object
          description: Register new entry
      responses:
        '200':
          description: OK