swagger: '2.0'
info:
  version: 1.0.0
  title: Bulk Issuance
  description: Bulk Issuance API
security:
  - hasRole: ["Issuer"]
securityDefinitions:
  hasRole:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://dummy.oauth.net/auth'
    tokenUrl: 'https://dumy.oauth.net/token'
    scopes:
      Issuer: scope of Issuer
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/{schemaName}/sample-csv:
    get:
      tags:
        - sampleTemplate
      summary: get sample template
      produces:
        - application/octet-stream
        - application/json
      parameters:
        - name: schemaName
          in: path
          required: true
          type: string
          description: schema name
      responses:
        '200':
          description: OK
          headers:
            Content-Disposition:
              type: string
          schema:
            $ref: '#/definitions/SampleTemplateResponse'
        '404':
          description: Not found
          schema:
            type: string
  /v1/uploads:
    get:
      tags:
        - uploadedFiles
      summary: get uploaded files
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: object
        '404':
          description: Not found
          schema:
            type: string
  /v1/{schemaName}/upload:
    post:
      tags:
        - uploadAndCreateRecords
      summary: upload the file and create records
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          description: Certification data in the form of csv
        - in: path
          name: schemaName
          type: string
          required: true
          description: Schema name you're uploading for
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/CreateRecordResponse'
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              message:
                type: string
        '404':
          description: Not found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
  /v1/{id}/report:
    get:
      tags:
        - downloadFileReport
      summary: download the success and error report of file uploaded
      produces:
        - application/json
        - application/octet-stream
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: File name
      responses:
        '200':
          description: OK
          headers:
            Content-Disposition:
              type: string
          schema:
            $ref: '#/definitions/FileDownload'
        '404':
          description: Not found
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string

definitions:
  SampleTemplateResponse:
    type: object
  UploadedFiles:
    type: object
  FileDownload:
    type: object
  CreateRecordResponse:
    type: object
  Group:
    type: object
    properties:
      roles:
        type: array
        items:
          type: string
  JWTClaimBody:
    type: object
    properties:
      token_type:
        type: string
      resource_access:
        type: object
        additionalProperties:
          $ref: "#/definitions/Group"
      realm_access:
        type: object
        properties:
          roles:
            type: array
            items:
              type: string
      scope:
        type: string
      preferred_username:
        type: string
      user_id:
        type: string
