version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  cred:
    image: cred
    build: .
    depends_on:
      - db
    ports:
      - '3333:3333'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      IDENTITY_BASE_URL: 
      SCHEMA_BASE_URL: 
volumes:
  data:
