version: '3'

services:
  db-test:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  cred-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db-test
    environment:
      DATABASE_URL: postgres://postgres:postgres@db-test:5432/postgres
      IDENTITY_BASE_URL: 
      SCHEMA_BASE_URL: 
